# Generated by Django 3.2.5 on 2021-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_listmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
